apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-role-binding
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>

    <match service-a>
      @type cloudwatch_logs
      log_group_name /gwangju/eks/application/logs
      log_stream_name service-a-logs
      auto_create_stream true
      region ap-northeast-2
      <buffer>
        flush_interval 5s
        chunk_limit_size 1M
        total_limit_size 5M
        retry_forever true
        retry_max_interval 30s
      </buffer>
    </match>

    <match service-b>
      @type cloudwatch_logs
      log_group_name /gwangju/eks/application/logs
      log_stream_name service-b-logs
      auto_create_stream true
      region ap-northeast-2
      <buffer>
        flush_interval 5s
        chunk_limit_size 1M
        total_limit_size 5M
        retry_forever true
        retry_max_interval 30s
      </buffer>
    </match>

    <match service-c>
      @type cloudwatch_logs
      log_group_name /gwangju/eks/application/logs
      log_stream_name service-c-logs
      auto_create_stream true
      region ap-northeast-2
      <buffer>
        flush_interval 5s
        chunk_limit_size 1M
        total_limit_size 5M
        retry_forever true
        retry_max_interval 30s
      </buffer>
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.10.3-debian-cloudwatch-1.0
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              memory: 200Mi
              cpu: 200m
          env:
            - name: AWS_REGION
              value: "ap-northeast-2"
            - name: FLUENT_UID
              value: "0"
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-svc
  namespace: fluentd
spec:
  selector:
    app: fluentd
  type: ClusterIP
  ports:
    - port: 24224
      targetPort: 24224
      protocol: TCP
