apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: wsi-ns
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /logs/app.log
        Tag           wsi

    [FILTER]
        Name          parser
        Match         wsi
        Key_Name      log
        Parser        daejeon-parser

    [FILTER]
        Name          lua
        Match         wsi
        script        transform.lua
        call          transform_log

    [OUTPUT]
        Name          cloudwatch_logs
        Match         wsi
        log_group_name /wsi/eks/log/
        log_stream_name log-${HOSTNAME}
        region         ap-northeast-2
        auto_create_group On

  parsers.conf: |
    [PARSER]
        Name          daejeon-parser
        Format        regex
        Regex         ^(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2}) (?<hour>\d{2}):(?<minute>\d{2}):(?<second>\d{2}),\d{3} - - (?<ip>[^ ]+) (?<port>\d+) (?<method>[^ ]+) (?<path>[^ ]+) (?<statuscode>\d+)$

  transform.lua: |
    function transform_log(tag, timestamp, record)
        local new_record = {}
        new_record["year"] = record["year"]
        new_record["month"] = record["month"]
        new_record["day"] = record["day"]
        new_record["hour"] = record["hour"]
        new_record["minute"] = record["minute"]
        new_record["second"] = record["second"]
        new_record["ip"] = record["ip"]
        new_record["port"] = record["port"]
        new_record["method"] = record["method"]
        new_record["path"] = record["path"]
        new_record["statuscode"] = record["statuscode"]
        return 1, timestamp, new_record
    end
