apiVersion: apps/v1
kind: Deployment

metadata:
  name: warm-deploy
  namespace: skills
  labels:
    app: warm

spec:
  replicas: 2
  selector:
    matchLabels:
      app: warm
  template:
    metadata:
      labels:
        app: warm
    spec:
      containers:
        - name: warm-container
          image: nginx
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
      restartPolicy: Always
